build: Add option to disable update checking
WerWolv/ImHex pull request #1036
Opened 2023-04-18 09:50 UTC by classabbyamp

This is aimed at use by linux distros, where package updates come from a central location, and users shouldn't need to worry about updating ImHex on their own. This disables parts of the ImHex UI that would not be useful in that case.

Tested and confirmed that this works in both states of the of the `-DIMHEX_DISABLE_UPDATE_CHECK` switch.

2023-04-18 09:50 UTC, classabbyamp commented on CMakeLists.txt
> +endif()
wasn't quite sure where to put this. I can move it if you have a better spot

2023-04-26 08:01 UTC, iTrooz commented
fine by me ! What do you think @WerWolv  ?

2023-04-30 16:20 UTC, WerWolv requested changes

2023-04-30 16:20 UTC, WerWolv commented on CMakeLists.txt
> +endif()
This here should definitely go into the `cmake/build_helpers.cmake` file instead.
Might need a bit of refactoring at some point but you can probably put it in `addVersionDefines` (or rename that function to `addDefines`)

2023-04-30 16:20 UTC, WerWolv commented on main/source/init/tasks.cpp
> +#ifdef HEX_UPDATE_CHECK
Use `#if defined(HEX_UPDATE_CHECK)` instead of ifdef

2023-04-30 16:20 UTC, WerWolv commented on main/source/init/tasks.cpp
> +#if HEX_UPDATE_CHECK
This should probably also use `#if defined`?

2023-04-30 16:20 UTC, WerWolv commented on plugins/builtin/source/content/settings_entries.cpp
> +#ifdef HEX_UPDATE_CHECK
Ditto

2023-04-30 16:20 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +#ifdef HEX_UPDATE_CHECK
Ditto

2023-04-30 16:21 UTC, WerWolv commented
Thanks a lot for the PR! I'm sorry it took so long for me to look at it

2023-05-05 20:03 UTC, WerWolv approved these changes

2023-05-05 20:03 UTC, merged