Fixed a number of errors and added some features to the IEEE745 tool. There are no issues reportimg these errors or feature request gor the added features.
WerWolv/ImHex pull request #1047
Opened 2023-04-27 00:59 UTC by paxcut

Errors and additions are described in the fork commit already. I'm not sure if I should repeat them here again. I have tested the changes thoroughly, but it is always possible  some fringe case was not tested and is incorrect. The tests were done using the many similar online calculators for IEEE 754 floating point formats.

2023-04-30 16:36 UTC, WerWolv requested changes

2023-04-30 16:36 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +            long long  exponentBits = ExtractBits(exponentBitPosition, exponentBitCount);
Any reason that you changed these values from `const auto` to `long long`? If you need a signed type, prefer `i64`.

2023-04-30 16:36 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +            if (std::popcount(static_cast<u64>(exponentBits)) == static_cast<long long>(exponentBitCount)) {
Should be `i64` again probably

2023-04-30 16:36 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +                    u32 precision =  ceil(1+mantissaBitCount*0.30102999566398);//    (exponentBitCount + mantissaBitCount + 1) / 4;
- `std::ceil` instead of `ceil`
- What does this magic number here mean? Is this really necessary? If yes, please define it as a `constexpr static auto` constant somewhere and give it a proper name

2023-04-30 16:36 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +            u32 precision =  ceil(1+mantissaBitCount*0.30102999566398);
Same thing as above. This can probably be cleaned up a bit

2023-04-30 16:36 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +            if (ImGui::InputText("hex.builtin.tools.ieee754.result.float"_lang, decimalFloatingPointNumberString, flags)) {
Try to stick to the same formatting style as the rest of ImHex uses.
For example, insert new lines, use spaces between `if` and the `(` and so on.
Also generatlly don't use the raw C functions such as `strtod` or `isnan` but use the ones in the `std::` namespace instead

2023-04-30 20:14 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +            long long  exponentBits = ExtractBits(exponentBitPosition, exponentBitCount);
There was no reason for the choice. I'll switch all variables that are I created as long long to i64.

2023-04-30 20:17 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +            if (std::popcount(static_cast<u64>(exponentBits)) == static_cast<long long>(exponentBitCount)) {
yes, though this code may not be relevant but I will incorporate all the suggestions to the new code before committing it.

2023-04-30 20:28 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                    u32 precision =  ceil(1+mantissaBitCount*0.30102999566398);//    (exponentBitCount + mantissaBitCount + 1) / 4;
the 0.301... is the value of log10(2). The quantity ceil(1+"mantissa bit count" * log10(2)) is a good approximation to the number of significant digits present in the decimal representation.  I can call the constant logBaseTenOfTwo. I am making the changes to my local clone where the new code that hasn't been committed to the fork lives, hence all the comments without code changes.

2023-04-30 20:42 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +            if (ImGui::InputText("hex.builtin.tools.ieee754.result.float"_lang, decimalFloatingPointNumberString, flags)) {
will do, sorry about working on changes in the middle of the review. I'll try to complete this soon but I am having some trouble with the addition of the display mode to the project file so it may take a little bit more time. I will also undo all changes to docs for languages other than those I am fluent and I may even skip those because I am not that confident in my ability as a translator. Thank you for your patience and continued support.

2023-05-14 09:16 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +            i64 signBits = ExtractBits(signBitPosition, 1);
I changed the types of all 8 byte signed integers to i64 as requested

2023-05-14 09:25 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                if (std::popcount(static_cast<u64>(exponentBits)) == static_cast<i64>(exponentBitCount)) {
Also made the requested change here.

2023-05-18 08:20 UTC, WerWolv requested changes

2023-05-18 08:20 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +            constexpr static auto logBaseTenOfTwo = 0.30102999566398119521373889472449L;
Constexpr variables in general should be PascalCase.

Also I think `logBaseTenOfTwo` deserves a name that better describes its functionality. 
Instead of hardcoding the value, you should also be able to just use `std::log10(2)` here. Most compilers have constexpr implementations for this function

2023-05-18 08:20 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +                    if (isThemeDark)
Instead of doing this manually, consider using `ImGui::BeginDisabled` and `ImGui::EndDisabled`. That automatically dimms the colors of all widgets in that block

2023-05-18 08:20 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +                        decimalFloatingPointNumberString = fmt::format("qnan");
Don't need to pass this through fmt::format

2023-05-18 08:20 UTC, WerWolv commented on plugins/builtin/source/content/tools_entries.cpp
> +                    std::string inputType;
This should probably be an enum and not a string

2023-05-18 08:20 UTC, WerWolv commented
Looks good for the most part, thank you!

2023-05-18 13:25 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +            constexpr static auto logBaseTenOfTwo = 0.30102999566398119521373889472449L;
I removed the constant and called the function instead as suggested.

2023-05-18 13:27 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                    if (isThemeDark)
Yes, using BeginDisabled does exactly what I wanted and it looks better this way. Changes as requested.

2023-05-18 13:31 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                u64 mask = ((u128(1) << (totalBitCount + 1)) - 1);
I switched to the suggested function and tested to make sure it was done correctly.

2023-05-18 13:32 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                        decimalFloatingPointNumberString = fmt::format("qnan");
Yes, sorry about that. Copilot syndrome...

2023-05-18 13:33 UTC, paxcut commented on plugins/builtin/source/content/tools_entries.cpp
> +                    std::string inputType;
I turned the string to an enum which should be faster and more readable.

2023-05-19 18:15 UTC, WerWolv approved these changes

2023-05-19 19:18 UTC, merged

2023-05-19 19:18 UTC, WerWolv commented
Thanks a lot!