Add some documentation
WerWolv/ImHex pull request #1052
Opened 2023-04-30 22:25 UTC by iTrooz

This PR adds some documentation. It's actually pretty random, I followed the function calls I was curious about and commented whenever I wasn't sure/I thought it needed clarification

You might want to make sure to squash them, because the commits are kind of a mess, I didn't went through the effort of interactive rebase

2023-04-30 22:28 UTC, iTrooz commented
Draft because I'm not sure I understand this code: https://github.com/WerWolv/ImHex/blob/ddcba81ed14689584481d1faddd149832f0e52bb/plugins/builtin/source/content/welcome_screen.cpp#L508

2023-05-04 17:21 UTC, WerWolv requested changes

2023-05-04 17:21 UTC, WerWolv commented on lib/libimhex/include/hex/api/imhex_api.hpp
> +         * the provider is user is actually editing.
Typo I think?

2023-05-04 17:21 UTC, WerWolv commented on lib/libimhex/include/hex/api/imhex_api.hpp
> +             * @param skipLoadInterface Whether to skip the provider's loading interface (see property documentation)
Did you mean "Provider documentation" here?

2023-05-04 17:21 UTC, WerWolv commented on lib/libimhex/include/hex/api/imhex_api.hpp
> +             * @param skipLoadInterface Whether to skip the provider's loading interface (see property documentation)
Same here

2023-05-04 17:21 UTC, WerWolv commented on lib/libimhex/include/hex/providers/provider.hpp
> +         * NOTE: This is not related to the EventProviderOpened event
These `NOTE:` can be replaced with the proper doxygen command `@note`

2023-05-04 17:21 UTC, WerWolv commented on lib/libimhex/include/hex/providers/provider.hpp
> +         * @brief true if there is any data that needs to be saved
These members are internal so they don't _really_ need any documentation. Nobody is able to use them anyways

2023-05-04 17:21 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +     * TODO add a button to load the default layout ?
Todos should probably not be in here

2023-05-04 17:21 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +        // sets a background when they are no views
Try to use capital letters at the start of comments

2023-05-04 17:35 UTC, iTrooz commented on lib/libimhex/include/hex/api/imhex_api.hpp
> +             * @param skipLoadInterface Whether to skip the provider's loading interface (see property documentation)
I was referring to the `m_skipLoadInterface` property: https://github.com/WerWolv/ImHex/blob/4912420d7eff8dc38a974158893c87355cb74726/lib/libimhex/include/hex/providers/provider.hpp#L160

What would you write ?

2023-05-04 17:39 UTC, iTrooz commented on plugins/builtin/source/content/welcome_screen.cpp
> +     * TODO add a button to load the default layout ?
Oh yeah, issues are probably better

2023-05-04 17:44 UTC, iTrooz commented on plugins/builtin/source/content/welcome_screen.cpp
> +        // sets a background when they are no views
Doing that now !

2023-05-05 20:01 UTC, WerWolv approved these changes

2023-05-05 20:02 UTC, merged