add subcommands system to CLI
WerWolv/ImHex pull request #1172
Opened 2023-06-30 19:15 UTC by iTrooz

System design has been discussed on discord

Should fix #948

2023-07-01 10:51 UTC, WerWolv requested changes

2023-07-01 10:51 UTC, WerWolv commented on lib/libimhex/include/hex/plugin.hpp
> + * This macro is used to define subcommands defined by the plugin/
Stray `/`

2023-07-01 10:51 UTC, WerWolv commented on lib/libimhex/include/hex/plugin.hpp
> +    [[gnu::visibility("default")]] std::vector<hex::SubCommand> subCommands
Is this truly portable? Won't name mangling apply to this in some cases? 
I think it would be better to define this variable as `static` and have a getter function similar to `getPluginName` which returns the commands.

I'm also not entirely sure how well this will work with plugins that are built out-of-tree since if the layout of std::vector is different in the plugin and the main application, this will segfault

2023-07-01 10:51 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +    void processArguments(std::vector<std::string> args){
Avoid copies here by passing as const&

2023-07-01 10:51 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +        if (args.size() == 0) return;
`args.empty()`

2023-07-01 10:51 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
Might be nice to have the option to specify multiple commands that are being executed one after the other. Not sure if that makes sense though

2023-07-01 10:51 UTC, WerWolv commented on main/source/main.cpp
> +    for(int i=1;i<argc;i++){
A bit weird formatting here

Also it might make sense to use `std::string_view` for all the arguments.
argc will be valid for the entire duration of the program so it's not necessary to copy the content around constantly

2023-07-01 10:51 UTC, WerWolv commented on plugins/builtin/source/plugin_builtin.cpp
> +        printf(
Use `hex::print` where needed

2023-07-01 10:51 UTC, WerWolv commented on plugins/builtin/source/plugin_builtin.cpp
> +            if (arg == "--" && !doubleDashFound) {
Not sure if I understand this code entirely. Does this mean people need to type `imhex -- fileToOpen.bin` when opening a file?  
I think this will break `Open As...` in the file explorer and drag-n-dropping files onto the executable

2023-07-01 12:12 UTC, iTrooz commented on lib/libimhex/include/hex/plugin.hpp
> +    [[gnu::visibility("default")]] std::vector<hex::SubCommand> subCommands
> Is this truly portable? Won't name mangling apply to this in some cases?

Honestly, I don't know C++ enough to tell

> I'm also not entirely sure how well this will work with plugins that are built out-of-tree since if the layout of std::vector is different in the plugin and the main application, this will segfault

Why would the layout of std::vector change, but not symbol names, or the size of other types ?

2023-07-01 12:15 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +    void processArguments(std::vector<std::string> args){
The problem is that I modify the vector in that function, so I can't use `const`. What would be the cleanest thing to do her ?

2023-07-01 12:25 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
Yeah, that could make sense ! I'm going to do that

2023-07-01 12:27 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +    void processArguments(std::vector<std::string> args){
Okay, https://github.com/WerWolv/ImHex/pull/1172#discussion_r1248768557 means I'm going to make multiple vectors anyway, so this problem isn't really relevant now

2023-07-01 12:31 UTC, iTrooz commented on plugins/builtin/source/plugin_builtin.cpp
> +            if (arg == "--" && !doubleDashFound) {
Essentially, this code just means we skip the first argument named `--`. It's kinda ugly, but I just really wanted to implement the fact that that `--` exists (because IIRC I've already seen it send to programs by the user environment)

So both `imhex -- fileToOpen.bin` and `imhex fileToOpen.bin` will work

2023-07-01 12:37 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
What do you think about the format `imhex --open file.txt /home/itrooz/file2.txt --othercmd --run-process ls al` ?

2023-07-01 13:00 UTC, WerWolv commented on lib/libimhex/include/hex/plugin.hpp
> +    [[gnu::visibility("default")]] std::vector<hex::SubCommand> subCommands
All the other functions just return pointers to trivial types whose layout will never change.
The size and layout of std::vector is not fixed and can change between standard library implementations and versions. 

The portable way to do it would be to make a C API around it

2023-07-01 13:01 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +    void processArguments(std::vector<std::string> args){
Ah if the data is being modified it's alright. I didn't see that, sorry

2023-07-01 13:02 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
Yeah I think that's okay. 
Also if you just run e.g `--version` multiple commands that don't require ImHex to start up fully, it would be nice if ImHex just exited after finishing the commands. Is that already how it works?

2023-07-01 13:06 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
Right now, `--help` calls exit() itself. We could do the same with `--version` without problem

2023-07-01 13:07 UTC, WerWolv commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
That would make `--version --help` only execute `--version` though

2023-07-01 13:10 UTC, iTrooz commented on lib/libimhex/source/subcommands/sub_commands.cpp
> +                        log::error("Multiple subcommands entered: {} and {}", selectedSubCommand->commandKey, args[0]);
The user would need to do `imhex --version --othercmd --help` anyway to execute both, and I don't think I've ever seen programs that handle both options like this.

2023-07-01 14:44 UTC, iTrooz commented on lib/libimhex/include/hex/plugin.hpp
> +    [[gnu::visibility("default")]] std::vector<hex::SubCommand> subCommands
Does this mean that the callback argumentscan't be a vector too ?

2023-07-01 17:10 UTC, WerWolv commented on lib/libimhex/include/hex/plugin.hpp
> +    [[gnu::visibility("default")]] std::vector<hex::SubCommand> subCommands
No that's okay. E.g returning a pointer to the struct would be okay

2023-07-04 13:57 UTC, iTrooz commented
Drafted because I realized there's going to be some problems with Windows support. You have some kind of "message sending" to existing window I haven't touched at all

2023-07-05 07:17 UTC, WerWolv commented
The message sending stuff is simply there that when you `Right click -> Open with -> ImHex` a file while there's already an ImHex window open, it will open that file in the open window instead of opening a new one. 
The receiving end is entirely implemented in the windowProc function and doesn't need to be touched at all I think. The sending end would need to be moved to the `--open` callback

2023-07-05 08:37 UTC, iTrooz commented
In that case we should probably expose an API so other plugins can do such a thing

2023-07-05 09:13 UTC, WerWolv commented
What features would be useful there? I can only really think of sending file paths over
Also this is highly OS dependent and is only implemented on Windows right now

2023-07-05 09:16 UTC, iTrooz commented
For example, What if Imhex is running and someone does `imhex --open a.txt --othercmd --run-process firefox` ? In that case, ImHex would open the file in the running instance, and open the process in a new one.

I think every callback should have the choice to forward data to a running instance

2023-07-12 18:52 UTC, WerWolv commented on lib/libimhex/include/hex/api/event.hpp
> +    EVENT_DEF(IsMainInstance, bool&);
This should probably rather be a getter-setter pair in `ImHexApi::System`. Similar to e.g the Portable version flag functions

2023-07-12 18:57 UTC, iTrooz commented on lib/libimhex/include/hex/api/event.hpp
> +    EVENT_DEF(IsMainInstance, bool&);
The problem is that we need to communicate with main to get this information (since main is the one doing the work), so we still need an event subscriber in main

2023-07-12 19:02 UTC, WerWolv requested changes

2023-07-12 19:02 UTC, WerWolv commented on main/source/window/win_window.cpp
> +                int nullIndex = -1;
Should probably be a `ssize_t`

2023-07-12 19:02 UTC, WerWolv commented on main/source/window/win_window.cpp
> +                std::vector<u8> evtData(messageData+nullIndex+1, messageData+messageSize);
Missing spaces between operands

2023-07-12 19:02 UTC, WerWolv commented on main/source/main.cpp
> +void initPlugins() {
This function doesn't actually initialize any plugins, it just loads them into our address space. The init function isn't being called until later when the Splash Screen is displayed

2023-07-12 19:02 UTC, WerWolv commented on plugins/builtin/source/plugin_builtin.cpp
> +        std::string version_str = hex::format("{} (Commit {}@{})", ImHexApi::System::getImHexVersion(), ImHexApi::System::getCommitBranch(), ImHexApi::System::getCommitHash());
`versionString`

2023-07-12 19:17 UTC, iTrooz commented on main/source/messaging/common.cpp
> +    std::optional<bool> s_isMainInstance;
Could you explain me why ? I don't really understand what "internal linkage" (which is what `static` means apparently ?) does

2023-07-12 19:19 UTC, iTrooz commented on main/source/messaging/linux.cpp
> +        std::logic_error("Not implemented");
This function should not even be called on Linux because https://github.com/WerWolv/ImHex/blob/e5473e9d8c3eb3a247eed760c4422eef6f75ee58/main/source/messaging/linux.cpp#L16 always returns true.

Calling this function on Linux/MacOS is a real bug from our part

I'll still replace it with a log::error() since we really don't want to crash ImHex, even if this would be a bug

2023-07-12 19:20 UTC, iTrooz commented on main/source/messaging/linux.cpp
> +        std::logic_error("Not implemented");
*Plus, I realized that I'm really dumb, and didn't even throw the exception. No idea what I was even thinking when making this code*

2023-07-12 19:21 UTC, WerWolv commented on lib/libimhex/include/hex/api/event.hpp
> +    EVENT_DEF(IsMainInstance, bool&);
Yeah but main can just set that flag at the start once in the ImHexApi. Just like the portable version flag.
And then it can be queried from there. That flag will never change afterwards

2023-07-12 19:21 UTC, WerWolv commented on lib/libimhex/source/api/imhex_api.cpp
> +                    throw std::runtime_error(hex::format("Forward event handler {} not found", evtName));
Fast-fail is okay but here people might lose a lot of progress if ImHex just crashes randomly when doing something

2023-07-12 19:21 UTC, WerWolv commented on main/source/messaging/common.cpp
> +    std::optional<bool> s_isMainInstance;
Internal linkage means "This variable cannot be accessed from any other file. It's a private local variable for this file."
If it's not static, it means this is a global variable and you can use `extern std::optional<bool> s_isMainInstance;` from another file to access it. We want to avoid this to not pollute the global namespace basically

2023-07-12 20:01 UTC, iTrooz commented on lib/libimhex/include/hex/api/event.hpp
> +    EVENT_DEF(IsMainInstance, bool&);
Done !

2023-07-13 12:07 UTC, WerWolv approved these changes

2023-07-13 12:08 UTC, merged