Linux memory provider
WerWolv/ImHex pull request #1331
Opened 2023-09-30 22:41 UTC by trumank

### Problem description

Implement a Linux backend for the ProcessMemoryProvider plugin.

### Implementation description

Most of the provider code is the same between Windows and Linux. The primary differences are:
- enumerate PIDs in `/proc/` to get the process list
- use `/proc/<PID>/cmdline` as the process name
- parse `/proc/<PID>/maps` to get the module list
- reading/writing from memory is done using `process_vm_readv`/`process_vm_writev`

NOTE: `sudo setcap CAP_SYS_PTRACE=+eip build/imhex` must be run to give the binary permission to read another process' memory. Running as root user should also work but I would not recommend it.

### Additional things
The existing translations keys no longer match since I moved the plugin from `windows` to `builtin`.

I'm not well versed in C++ so I attempted to keep my changes rather simple. Feedback is very welcome.

2023-09-30 22:55 UTC, Nowilltolife requested changes

2023-09-30 22:55 UTC, Nowilltolife commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +            // TODO error handling strerror(errno)
Can you expand this TODO before submiting the PR?

2023-09-30 22:55 UTC, Nowilltolife commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +                buffer << file.rdbuf();
The use of a string stream for string conversion seems rather expensive, is there no other way?

2023-09-30 22:55 UTC, Nowilltolife commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +                tokens.push_back(token);
prefer using a vector construction using iterators like this:
```c++
        std::vector<std::string> tokens{std::istream_iterator<std::string>{iss},
                                       std::istream_iterator<std::string>{}};
```

2023-09-30 22:55 UTC, Nowilltolife commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +            u64 end = std::stoull(endStr, nullptr, 16);
this can be compacted using stream operators:
```c++
u64 start, end;
char hyphen;

rangeStream >> std::hex >> start >> hyphen >> end;
```

2023-09-30 22:55 UTC, Nowilltolife commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +            // TODO error handling strerror(errno)
"

2023-10-01 00:07 UTC, trumank commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +                buffer << file.rdbuf();
A cursory search didn't turn up anything very concise. Is there a better way to read a file to a string?

2023-10-01 00:08 UTC, trumank commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +            // TODO error handling strerror(errno)
Ah right, I neglected to note my concern in the PR description. `process_vm_readv` will fail without the `CAP_SYS_PTRACE` capability so would make sense to propagate this error to the user so permissions can be fixed. How are errors like these best handled?

2023-10-04 20:17 UTC, WerWolv requested changes

2023-10-04 20:17 UTC, WerWolv commented on plugins/builtin/include/content/providers/process_memory_provider.hpp
> +#ifdef _WIN32
We generally use `#if defined()` instead of `#ifdef` and we also have defines available so you don't need to rely on the system ones. `OS_WINDOWS` and `OS_LINUX` is what other code uses mainly

2023-10-04 20:17 UTC, WerWolv commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +            // TODO error handling strerror(errno)
It's difficult right now to show errors like that from the read/write functions. You can only properly return errors from the open function

2023-10-04 20:17 UTC, WerWolv commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +                buffer << file.rdbuf();
Definitely don't use `std::ifstream` but our own `wolv::io::File` class which is a wrapper around the C File API.
This also lets you just read the entire content of the file to a std::string without having to rely on any streams

2023-10-04 20:17 UTC, WerWolv commented on plugins/builtin/include/content/providers/process_memory_provider.hpp
> +                    { "hex.builtin.provider.process_memory.process_name"_lang, this->m_selectedProcess->name },
Since you renamed those strings here, don't forget to also adjust them in all the localization files in the romfs

2023-10-04 20:17 UTC, WerWolv commented on plugins/builtin/source/content/providers/process_memory_provider.cpp
> +        std::ifstream file(std::fs::path("/proc") / std::to_string(this->m_processId) / "maps");
This should also be replaced with the API mentioned above

2023-10-04 20:17 UTC, WerWolv commented
Amazing work, thanks a lot!

2023-11-05 00:55 UTC, xtexChooser commented
ptrace should also be enabled for flatpak, I think. [like this](https://github.com/xtexChooser/ImHex/commit/393f28af658c09ca4b39041dcd07129fbc707450)
```patch
From 393f28af658c09ca4b39041dcd07129fbc707450 Mon Sep 17 00:00:00 2001
From: xtex <xtexchooser@duck.com>
Date: Sun, 5 Nov 2023 08:51:58 +0800
Subject: [PATCH] Allow ptrace in Flatpak sandbox

Signed-off-by: xtex <xtexchooser@duck.com>
---
 dist/net.werwolv.ImHex.yaml | 1 +
 1 file changed, 1 insertion(+)

diff --git a/dist/net.werwolv.ImHex.yaml b/dist/net.werwolv.ImHex.yaml
index 28f0118..022289d 100644
--- a/dist/net.werwolv.ImHex.yaml
+++ b/dist/net.werwolv.ImHex.yaml
@@ -10,6 +10,7 @@ finish-args:
   - --socket=x11
   - --filesystem=host
   - --device=all
+  - --allow=devel
 
 modules:
   - name: libiconv
-- 
2.42.0

```

2023-11-12 16:55 UTC, iTrooz commented
@trumank Hey, do you plan to continue working on this ? If not, I'd like to pick it up at some point in the future

2023-11-12 18:23 UTC, trumank commented
> @trumank Hey, do you plan to continue working on this ? If not, I'd like to pick it up at some point in the future

Hey! I may at some point but if you want to pick it up before that happens, feel free.

One thing I should note is that `/proc` files report zero size (https://stackoverflow.com/a/58920635) so `wolv::io::File` won't work as-is as it attempts a stat to determine how large a buffer to read.

2023-11-14 11:29 UTC, WerWolv commented
Using `wolv::io::File` should work in general, you just need to tell it the size to read manually using `file.readVector(1000)`. That will try to read 1000 bytes from the file instead of trying to query the size from the file. In this case here, I'd just try to read maybe 1MiB from that file. If it's less than that, the function will just return a smaller vector containing the data.

2023-12-07 21:53 UTC, WerWolv approved these changes

2023-12-07 22:33 UTC, merged