feat(lang): add search options for string encoding and endianness
WerWolv/ImHex pull request #1490
Opened 2024-01-13 11:06 UTC by PerikiyoXD

Added search options for string encoding (UTF-8, UTF-16, UTF-32) and endianness (Little, Big) in the hex editor. This enhancement allows users to customize the search process based on different string encodings and byte orders.

Affected files:
- `plugins/builtin/romfs/lang/de_DE.json`
- `plugins/builtin/romfs/lang/en_US.json`
- `plugins/builtin/romfs/lang/es_ES.json`
- `plugins/builtin/romfs/lang/it_IT.json`
- `plugins/builtin/romfs/lang/ja_JP.json`
- `plugins/builtin/romfs/lang/ko_KR.json`
- `plugins/builtin/romfs/lang/pt_BR.json`
- `plugins/builtin/romfs/lang/zh_CN.json`
- `plugins/builtin/romfs/lang/zh_TW.json`
- `plugins/builtin/source/content/views/view_hex_editor.cpp`

Resolves: #1325

2024-01-14 23:40 UTC, PerikiyoXD commented
Should be ready to ship!

2024-01-15 18:43 UTC, WerWolv requested changes

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/include/content/popups/hex_editor/popup_hex_editor_find.hpp
> +    enum class StringModeEndianness : u8 {
I generally use `std::endian` for this

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/romfs/lang/de_DE.json
> +        "hex.builtin.view.hex_editor.search.string.encoding": "Kodierung",
Only add translations for the languages you actually know. It's better to have no translation (and just fallback to english) than having extremely cryptic translations

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/include/content/popups/hex_editor/popup_hex_editor_find.hpp
> +using namespace hex;
Never use `using namespace` in a header or global scope

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +using namespace hex;
Everything here should be encapsulated in the `hex::plugin::builtin` namespace instead of doing this

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                "UTF-8",
Use the localization strings you've added here

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                    "Little endian",
Same here. I think there's even some translations in the ui plugin library that you can use. `hex.ui.common.something`

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +            if (ImGuiExt::InputTextIcon("##input", ICON_VS_SYMBOL_NUMERIC, m_input, ImGuiInputTextFlags_EnterReturnsTrue | ImGuiInputTextFlags_AutoSelectAll | ImGuiInputTextFlags_CharsHexadecimal)) {
I usually like to add new lines before/after control flow statements and "logical block" to make things a bit more readable.

2024-01-15 18:43 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                    auto swapEndianess = [](auto &value, std::endian endian, StringModeEncoding encoding) {
There's byteswap utilities in `<hex/helpers/utils.hpp>`. No need to use intrinsics

2024-01-18 11:27 UTC, PerikiyoXD commented
To clarify changes, I've refactored the code a bit, extracted the popup code to it's own header and source file, extracted the input processing to only trigger when needed and tweaked the UI a bit.

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                auto statusString = "No more results";
Missing translation here

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +            // TODO: Implement this
This TODO looks outdated? The functionality seems to be implemented but there's some commented code here that should be removed

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +        static std::array EncodingNames = {
These two arrays can't be `static`. Otherwise the translation will only be initialized the first time and then never be updated again, even if the language changes

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                                      m_stringEncoding == Encoding::UTF8)) {
Personally I'd remove that new line, it makes it a bit hard to read

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +                                      EndiannessNames[std::underlying_type_t<Endianness>(m_stringEndianness.load())])) {
`std::to_underlying(...)`

2024-01-18 19:26 UTC, WerWolv commented on plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
> +} // namespace hex::plugin::builtin
While this is a decent comment, this would be the only one in the entire project

2024-01-27 13:13 UTC, merged