impr: Added CSV and TSV as export options for Find results
WerWolv/ImHex pull request #1673
Opened 2024-05-13 22:39 UTC by SparkyTD

### Problem description
The default result export functionality of the Find tool is limited to only exporting data in a nonstandard text format. This PR adds support for exporting the results in either CSV or TSV format. The PR also removes the old format.

### Implementation description
I added the classes `ExportFormatter`, `ExportFormatterCsv` and `ExportFormatterTsv`, with similar implementations to the pattern data exporters.

I also moved the `ViewFind::Occurrence` class into `hex/helpers/types.hh`, so the exporters can access it.

### Screenshots
![image](https://github.com/WerWolv/ImHex/assets/45818400/25ef99b6-0710-4fc9-a91c-419720e4e46c)

### Additional things
Another small change I made is moving the "{} entries found" line on the same line as the Search and Reset buttons. I think it looks cleaner this way, but if anyone disagrees, I can revert it.

2024-05-13 23:14 UTC, SparkyTD commented
The CSV/TSV exporters have been tested by finding 5 character longs strings in /dev/urandom, and all the escaping logic seems to work as it's supposed to.

As for JSON, the nlohmann library already takes care of escaping strings.

2024-05-14 02:19 UTC, SparkyTD commented
There is an issue that causes the format selector popup to stay visible behind the main window in some cases when the user clicks the parent window. The bug also exists in the original pattern export popup. I haven't been able to fix it yet.

![image](https://github.com/WerWolv/ImHex/assets/45818400/6d677855-ef31-4579-ba10-561f5b04e277)

2024-05-19 12:31 UTC, WerWolv commented
Thanks a lot for the work!
I'd suggest adding these exporter registration things to the Content Registry instead, that way other plugins can re-use the same infrastructure you already wrote to add their own formatters. The Occurrences struct as well because now it's being imported by basically every single file in ImHex which is probably not needed :D

The actual implementations of the formatters can stay in the builtin plugin like it is

2024-06-18 15:58 UTC, iTrooz commented
@WerWolv Do you think this is ready to be merged ?

2024-06-18 16:04 UTC, iTrooz approved these changes

2024-06-18 16:04 UTC, iTrooz commented on lib/libimhex/include/hex/api/content_registry.hpp
> +                const std::vector<ExporterEntry>& getExporterEntries();
Could you document the difference between getEntries() and getExporterEntries() ?

2024-06-18 16:04 UTC, iTrooz commented on plugins/builtin/include/content/export_formatters/export_formatter.hpp
> +    class ExportFormatter {
Could you document this class ?

2024-06-18 16:05 UTC, iTrooz requested changes
My bad, I marked this as "approved" instead of "request changes"

2024-06-18 16:47 UTC, iTrooz commented on plugins/builtin/include/content/export_formatters/export_formatter.hpp
> +    class ExportFormatter {
Ok ! Thanks

2024-06-18 16:47 UTC, iTrooz approved these changes

2024-06-18 20:57 UTC, merged