Fixed the installation directory on Linux
WerWolv/ImHex pull request #168
Opened 2021-02-20 19:16 UTC by Mailaender

The main underlying problem is that ImHex does not (yet) adhere to https://refspecs.linuxfoundation.org/fhs.shtml and https://specifications.freedesktop.org/basedir-spec so I covered cmake with workarounds. Sorry.

2021-03-16 05:57 UTC, Tatsh commented on cmake/build_helpers.cmake
> +        install(TARGETS libimhex DESTINATION ${CMAKE_INSTALL_LIBEXECDIR}/imhex)
I think this should go in `CMAKE_INSTALL_LIBDIR`. By default that's in search paths.

2021-03-16 06:09 UTC, Tatsh commented
Also please see my patch: https://github.com/Tatsh/tatsh-overlay/blob/master/app-editors/imhex/files/imhex-installation.patch

2021-03-16 06:11 UTC, Tatsh requested changes

2021-03-20 16:39 UTC, Mailaender commented on cmake/build_helpers.cmake
> +        install(TARGETS libimhex DESTINATION ${CMAKE_INSTALL_LIBEXECDIR}/imhex)
Yep, that's way better.

2021-03-20 16:39 UTC, Mailaender commented on cmake/build_helpers.cmake
> +            install(FILES "$<TARGET_FILE:${plugin}>" DESTINATION ${CMAKE_INSTALL_LIBEXECDIR}/imhex/plugins/)
Nope, plugins are binary and are not allowed in DATADIR according to FHS.

2021-03-20 16:39 UTC, Mailaender commented on cmake/build_helpers.cmake
> +            install(FILES ${CMAKE_CURRENT_BINARY_DIR}/wrapper DESTINATION ${CMAKE_INSTALL_BINDIR} RENAME imhex PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WOR
Removed it.

2021-03-20 16:44 UTC, Mailaender commented
I redid this according to your patch which works really well. I only changed plugin path and lower cased (as that was done to the binary as well recently) the paths. Tried to rebase this, but it seems a lot has changed. I also don't fully understand the changes. Everything seems to be pulled from XDG user directories on Linux which makes no sense. I guess we will have to patch this all over again for the next release. :(

2021-03-20 16:47 UTC, Mailaender commented on cmake/build_helpers.cmake
> +            install(FILES ${CMAKE_CURRENT_BINARY_DIR}/wrapper DESTINATION ${CMAKE_INSTALL_BINDIR} RENAME imhex PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WOR
Though that makes ImHex put its config files at the location where you type the execution command...

2021-03-20 16:50 UTC, Mailaender commented
https://build.opensuse.org/request/show/880264

2021-09-21 19:34 UTC, closed without merging