Install files in their proper paths on linux
WerWolv/ImHex pull request #183
Opened 2021-02-28 18:07 UTC by roblabla

This makes sure everything goes in their proper FHS paths on linux, while (hopefully) keeping the current paths on windows and macos.

2021-02-28 20:49 UTC, WerWolv requested changes

2021-02-28 20:49 UTC, WerWolv commented on plugins/libimhex/CMakeLists.txt
> +target_include_directories(libimhex PUBLIC include ${XDGPP_INCLUDE_DIRS})
`${XDGPP_INCLUDE_DIRS}` should be added to the line below instead of having two `target_include_directories` directives

2021-02-28 20:49 UTC, WerWolv commented on plugins/libimhex/source/helpers/utils.cpp
> +                    transform(dataDirs.begin(), dataDirs.end(), back_inserter(result),
This should be `std::transform` and `std::back_inserter`. Where's the `using namespace std` leak coming from? xdg?

2021-02-28 20:49 UTC, WerWolv commented on plugins/libimhex/source/helpers/utils.cpp
>      #include <unistd.h>
Those three includes can be removed now. They were only there for the old home directory detection

2021-02-28 23:27 UTC, roblabla commented on plugins/libimhex/source/helpers/utils.cpp
> +                    transform(dataDirs.begin(), dataDirs.end(), back_inserter(result),
got no clue, I checked the xdgpp.hpp file out, it doesn't contain using namespace std.

2021-02-28 23:35 UTC, roblabla commented
All fixed. Dunno where the `using namespace std;` comes from, but that doesn't seem to be related to this PR?

2021-03-01 07:48 UTC, WerWolv commented
Yeah I also can't find it anywhere. 
Fixes look good though. Thank you :)

2021-03-01 07:48 UTC, merged