Inline visualizers in custom data inspectors
WerWolv/ImHex pull request #1966
Opened 2024-11-23 21:56 UTC by paxcut

### Problem description
This PR aims at making inline visualizers work on the data inspector so that more rgb encodings can be added as custom pattern language inspector rows. This was never setup to work because the inline visualizer rendering function was a private member function.

### Implementation description
In order to be accessible from the inspector class the rendering function was made public.

### Additional things
Missing still is the tooltip to make it behave like other color entries.

2024-11-24 10:36 UTC, WerWolv requested changes

2024-11-24 10:36 UTC, WerWolv commented on plugins/builtin/source/content/views/view_data_inspector.cpp
> +                    auto drawer = std::make_unique<hex::ui::PatternDrawer>();
This causes a lot of unnecessary allocations every single frame. Instead, I believe the PatternDrawer shouldn't be involved at all in rendering this

2024-11-28 17:52 UTC, WerWolv requested changes

2024-11-28 17:52 UTC, WerWolv commented on plugins/ui/source/ui/pattern_drawer.cpp
> +                m_lastVisualizerError = m_visualizerDrawer.getLastVisualizerError();
It doesn't look like `m_lastVisualizerError` is really needed anymore. Keeping the error message only stored in the visualizer drawer would be better

2024-11-28 19:39 UTC, paxcut commented on plugins/ui/source/ui/pattern_drawer.cpp
> +                m_lastVisualizerError = m_visualizerDrawer.getLastVisualizerError();
I deleted the variable as requested and added function to clear the error on VisualizerDrawer to make it easier. I simulated a code error in my Inspector rgba5551 visualizer and I got a nice popup error of the reason why it wasn't working. Fixing the error made the visualizer work again so it looks like at a basic level it is working.

2024-11-29 16:20 UTC, merged