Feat: Added clickable links to error messages.
WerWolv/ImHex pull request #1988
Opened 2024-12-05 08:55 UTC by paxcut

Errors printed in the console can be clicked to have the cursor jump to the source code line where the error is at. 

The mouse cursor changes its shape to indicate which parts of the error message can be clicked on the console. When the cursor jumps, the text editor takes the focus away from the console and it scrolls the window to make the line with the error is visible if it isn't. This code uses the function created for the go-to PR but adds code to switch focus to the target. When the codes are merged please keep both the part that jumps the cursor and the part that sets the focus.

2024-12-05 19:01 UTC, WerWolv requested changes

2024-12-05 19:01 UTC, WerWolv commented on lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
> +            bool type1 = lineText.find("E: <Source Code>:") == 0;
These strings are Pattern Language specific. To keep the text editor modular, I'd suggest making this configurable from outside instead of hardcoding it. Maybe through some callback that returns the character for where where the box should be drawn on this line

2024-12-05 19:10 UTC, paxcut commented on lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
> +    using ErrorHoverBoxes = std::map<Coordinates, ErrorHoverBox>;
It is just placed after defining the type it depends on (ErrorHoverBox). The other two are placed after defining their types, but both work together so I prefer them to be next to each other.

2024-12-05 19:14 UTC, WerWolv commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> +        m_textEditor.ClearErrorMarkers();
The separate functions should still exist, just add an extra function that calls them all

2024-12-05 20:15 UTC, paxcut commented on lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
> +            bool type1 = lineText.find("E: <Source Code>:") == 0;
The box for errors is the entire line. The strings cannot be configured and have to match the specified values to guarantee that clicking them will change the cursor and the focus somewhere in the file opened in the pattern editor. 

The strings are themselves hard-coded by various parts of ImHex that the text editor has no access to. For example the string "<Source Code>" is defined in api.hpp and the rest is defined in error.hpp in the pattern language.

2024-12-05 20:29 UTC, WerWolv commented on lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
> +            bool type1 = lineText.find("E: <Source Code>:") == 0;
What I meant is, the strings "E: <Source Code>" only have a meaning for ImHex and the pattern language. Nothing else. If we want to use the text editor in another project later or even just want to use that click-to-jump feature elsewhere in ImHex, we cannot because it's hardcoded to only ever work with this specific output. Instead it would be better if this detection happened in ImHex (in the view_pattern_editor.cpp file) instead of in the TextEditor library

2024-12-06 00:06 UTC, paxcut commented on lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
> +                ImGui::Text("%s", mErrorText.c_str());
Changed code to process unformatted text using TextUnformatted().

2024-12-06 00:12 UTC, paxcut commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> +        m_textEditor.ClearErrorMarkers();
I wrote the function that clears all actionable class instances and used it to clear the text editor and the console editor instances.

2024-12-06 00:19 UTC, paxcut commented on lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
> +            bool type1 = lineText.find("E: <Source Code>:") == 0;
Of course. That makes sense once explained. I changed the part that processes the possible targets to go through an arbitrary number of strings to match defined in a variable.The line and column index must follow the strings that are stored and the strings must be at the start of the line. The strings get loaded when the console editor is created in view pattern editor.

2024-12-06 21:45 UTC, merged

2024-12-06 21:45 UTC, WerWolv commented
Thank you!