Fix: patterns popup
WerWolv/ImHex pull request #225
Opened 2021-04-20 16:42 UTC by ThisALV

This PR fixes two minor issues:
- Available .hexpat list not cleaned between each scan
- .hexpat list popup not showing up first time it is opened, which is problematic for usage of command-line argument / recent files to open file at startup

As a side effect, pattern editor view is now dismissed while .hexpat list is open, but it show up again as soon as popup has been closed.

2021-04-20 19:51 UTC, WerWolv requested changes
Thanks a lot for the PR, I didn't even realize it was broken

2021-04-20 19:51 UTC, WerWolv commented on source/views/view_pattern.cpp
> +            m_possiblePatternFiles.clear();
Use `this->` to match style used elsewhere

2021-04-20 19:51 UTC, WerWolv commented on source/views/view_pattern.cpp
> +        if (!ImGui::IsPopupOpen("hex.view.pattern.accept_pattern"_lang)) {
I'm not sure I understand what you're doing here. This will cause the pattern source window to disappear completely while the "accept pattern" popup is shown.

2021-04-21 14:52 UTC, ThisALV commented on source/views/view_pattern.cpp
> +        if (!ImGui::IsPopupOpen("hex.view.pattern.accept_pattern"_lang)) {
Yes, and if it was open, it will show up again as soon as "Accept pattern" popup is gone.
It's the only clear way I found to address that issue, and as "Accept pattern" was a modal popup anyways, I don't think it should matter.

2021-05-04 12:12 UTC, ThisALV commented
Hi. As this PR didn't have any activity for a while, I was wondering if it is okay and if it can be merged into master.

2021-05-18 16:28 UTC, closed without merging