fix: don't drop defines after include
WerWolv/ImHex pull request #433
Opened 2022-02-12 09:23 UTC by Diadlo

2022-02-12 14:39 UTC, WerWolv requested changes

2022-02-12 14:39 UTC, WerWolv commented on lib/libimhex/source/pattern_language/preprocessor.cpp
> +                        auto preprocessedInclude = preprocessor.preprocess(file.readString(), /*initialRun =*/false);
Since nothing depends on initialRun anymore now, this can just be removed completely. It was originally used for recursive pre-processing of the input but that's now handled better by creating multiple preprocessor instances when doing that

2022-02-12 18:40 UTC, Diadlo commented on lib/libimhex/source/pattern_language/preprocessor.cpp
> +                        auto preprocessedInclude = preprocessor.preprocess(file.readString(), /*initialRun =*/false);
Actually, depends. At least now we clear set of defines and pragmas at the beginning of the `preprocess` function if it's "initial" pass. It looks reasonable that we start preprocessing with empty set and don't clear it when process includes

2022-02-13 10:49 UTC, WerWolv approved these changes

2022-02-13 10:50 UTC, merged