feature: User now can add custom directories
WerWolv/ImHex pull request #444
Opened 2022-02-17 18:35 UTC by PredatorCZ

Helo.
Created new setting category, where user can specify custom directories.
Custom dirs are only used for patterns, pattern includes, python scripts, magics, yara rules, constants and encodings.
Main reason is that anyone might want to use multiple git repos or sources for such files.
Not implemented for macos, because it uses only one path, but can be implemented as well.

Also added ux change, where setting categories are sorted the way they were actually created instead of alphabetical order.

Tested on linux.

2022-02-17 20:43 UTC, WerWolv commented
Thanks a lot! This looks great

2022-02-17 20:59 UTC, WerWolv requested changes

2022-02-17 20:59 UTC, WerWolv commented on plugins/builtin/source/lang/en_US.cpp
> +                { "hex.builtin.setting.folders", "Folders" }
This belongs further up (Line 677) below the other settings related strings I think

2022-02-17 20:59 UTC, WerWolv commented on plugins/builtin/source/content/settings_entries.cpp
> +        ContentRegistry::Settings::add(dirsSetting, dirsSetting, std::vector<std::string> {}, [](auto name, nlohmann::json &setting) {
This UI might benefit from a small help text explaining what it's actually doing.
Just a short text like "Adding folders here will cause ImHex to consider them as search paths for patterns, includes, magic files, etc."

2022-02-17 20:59 UTC, WerWolv commented on lib/libimhex/source/api/content_registry.cpp
> +        std::vector<std::string> getStringVector(const std::string &unlocalizedCategory, const std::string &unlocalizedName) {
I'd call this `getStringArray` because JSON refers to it as array

2022-02-18 20:25 UTC, PredatorCZ commented on plugins/builtin/source/content/settings_entries.cpp
> +        ContentRegistry::Settings::add(dirsSetting, dirsSetting, std::vector<std::string> {}, [](auto name, nlohmann::json &setting) {
I added new methods for adding descriptions for categories.
They override header line that is under tabs, so the description doesn't waste space.

2022-02-18 21:34 UTC, WerWolv approved these changes

2022-02-18 21:34 UTC, WerWolv commented on plugins/builtin/source/content/settings_entries.cpp
> +        ContentRegistry::Settings::add(dirsSetting, dirsSetting, std::vector<std::string> {}, [](auto name, nlohmann::json &setting) {
Thank you!

2022-02-18 21:34 UTC, merged