Move logic to draw GUI into separate class
WerWolv/ImHex pull request #472
Opened 2022-03-12 16:56 UTC by Diadlo

2022-03-15 23:03 UTC, WerWolv commented
Thank you!
Could you explain a bit what advantages this brings over the way I did it so far?

2022-03-15 23:09 UTC, WerWolv requested changes

2022-03-15 23:09 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_array_dynamic.hpp
> +        void accept(PatternVisitor &v) override {
I think it might be nicer to make these functions all private and add the PatternVisitor class as a friend class to the various classes so they are only accessible by the visitor.

That way we also wouldn't need to add various getters to the Pattern classes that are only ever used by the visitor

2022-03-15 23:09 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
These visit functions should all be able to be marked as `const` and with that also take the pattern either as a `const PatternXYZ *` or a `const Pattern &`

2022-03-15 23:09 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +    class ImGuiDrawer : public PatternVisitor
I'd rather call this PatternDrawer or PatternRenderer since it doesn't really have much to do with ImGui

2022-03-16 05:48 UTC, Diadlo commented
> Could you explain a bit what advantages this brings over the way I did it so far?

Some time ago I started implementing JSON builder and it should went over the patterns to do its job. But here we lead to a situation where we places all possible pattern handlers in patterns itself. It makes classes overloaded with logic (provide data about concrete pattern + draw GUI + build JSON). Formally we can leave drawing as is and only add visitor for JSON builder, but I think it's better to make it in a generic way.

2022-03-16 05:52 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +    class ImGuiDrawer : public PatternVisitor
I don't understand you. I'm going to rename it, but why do you think it doesn't have much to do with ImGui? This class is full of ImGui calls. It can draw GUI only for ImGui

2022-03-16 05:55 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
I thought about it. Formally `visit` not necessary doesn't modify incoming patterns (here it's part of an abstract interface).
Furthermore, I've tried to make it const and faced some issues since some internal functions wasn't const. I can retry and come to you with concrete cases.

2022-03-16 06:03 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_array_dynamic.hpp
> +        void accept(PatternVisitor &v) override {
For me **now** `Pattern` is more like an information provider, so I don't see any issues with adding getters. Now we decrease coupling between drawing logic and providing an information, but `friend` will increase it back. Are you sure, that it's necessary? What advantages it will provide? Less code?

I think rule of thumb is using functions even to access data because with it we can easily refactor internal logic. For example we can add value caching or vice versa calculate value instead of storing it

2022-03-16 07:39 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +    class ImGuiDrawer : public PatternVisitor
I just like to name things after the thing they're fullfilling, not after things that are more or less implementation details.
I could replace ImGui with some other renderer in there if I wanted and for everything outside of that class, nothing changes.

2022-03-16 07:41 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_array_dynamic.hpp
> +        void accept(PatternVisitor &v) override {
My thought was that there's a lot of weird functions in some of the Patterns now that don't serve much purpose but to expose implementation details. But yeah, you're right with the decoupling, it would make it worse as friends.

2022-03-16 15:21 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +    class ImGuiDrawer : public PatternVisitor
Done

2022-03-16 15:43 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
Yep. The issue is changing `displayEnd` for arrays

2022-03-16 15:47 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
We can make it `mutable`, but should we? As I said it's ok to modify value inside a visitor

2022-03-16 15:50 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
Hm. But acually it's part of display logic. Should we store it in Pattern?

2022-03-16 16:00 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
Since you've moved all drawing logic out, I'd also move out all variables that are only needed for displaying if possible. 
It might not be possible with displayEnd though since that needs to be handled per-pattern

2022-03-16 20:46 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
I will try to handle it with `map` that will match Pattern -> displayEnd in `PatternDrawer`

2022-03-17 06:14 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/imgui_pattern_drawer.hpp
> +        void visit(PatternArrayDynamic& pattern) override {
`displayEnd` is moved. But `const` still can't be used because `formatDisplayValue` accepts `Token::Literal` which is `std::variuant` with non-const `Pattern` pointer

2022-03-17 22:36 UTC, WerWolv commented
Had to fix some smaller issues with the pattern drawing and that created a bunch of conflicts here, sorry. It's not super big changes luckily

2022-03-18 05:15 UTC, Diadlo commented
I rebased the branch. Hope I didn't miss anything

2022-03-18 23:34 UTC, WerWolv commented
Thank you!
I just tried it out a bit and it seems to work really good. Two things though. 

- Patterns can't really be selected / clicked on anymore. Hovering over the lines makes them highlight for one frame and then disappear again.
- Since we have a nice interface now that we can expand upon, it might be smart to move all the pattern drawing files to the builtin plugin so the pattern language implementation is completely imgui-free. What do you think about that?

2022-03-19 08:25 UTC, Diadlo commented
Is `u8 arr[100]` static array?

If so, I can't reproduce the issue

https://user-images.githubusercontent.com/6306608/159113688-f61325e7-99c3-4802-9129-9930027fe90a.mp4

2022-03-19 08:27 UTC, Diadlo commented
Is `u8 arr[100]` static array?

If so, I can't reproduce. Can you share an example of pattern with issue?

https://user-images.githubusercontent.com/6306608/159113756-6dc4595f-cde6-4745-ac7c-6ed56c962116.mp4

2022-03-19 08:31 UTC, Diadlo commented
> Since we have a nice interface now that we can expand upon, it might be smart to move all the pattern drawing files to the builtin plugin so the pattern language implementation is completely imgui-free. What do you think about that?

Actually, I don't really understand the logic of this division right now, if you think it's better, let's move it. If you don't mind, I'd prefer to do it in a separate PR to reduce potential conflicts

2022-03-19 10:50 UTC, WerWolv commented
> Is u8 arr[100] static array?
> If so, I can't reproduce. Can you share an example of pattern with issue?

I triggered it with 
```cpp
struct Test {
    u32 x;
};

Test test[10] @ 0x00;
```

> Actually, I don't really understand the logic of this division right now, if you think it's better, let's move it. If you don't mind, I'd prefer to do it in a separate PR to reduce potential conflicts

I thought about this before since it felt weird to have ImHex built-in functionality specific stuff in libimhex which should be a common thing to use by all plugins. 
But we / I can tackle that later, that's okay.

2022-03-19 11:34 UTC, Diadlo commented
> I triggered it with

Still can't reproduce. Please, make sure that you fetched the latest version to test, since there was issue like this in one of the previous versions

2022-03-20 22:49 UTC, WerWolv commented
You're right, I tested it again now and it didn't happen anymore

2022-03-20 23:00 UTC, WerWolv requested changes
Some more style nit-picks. Other than that it's looking great. Thank you!

2022-03-21 08:27 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/pattern_drawer.hpp
> +        template<class SomePattern>
Unfortunatly, we can't use this. This function accepts both `PatternArrayDynamic` and `PatternArrayStatic` and only them. Because they have `forEachArrayEntry` method. I can create an interface `PatternArray` with this method, if you want.

For now renamed to `ArrayPattern` to make the intention more clear.

2022-03-21 08:27 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/pattern_drawer.hpp
> +    const u64 DISPLAY_END_DEFAULT = 50;
Done, but can you clarify why is `static` needed here?

2022-03-21 08:27 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_float.hpp
> +                assert(false);
Good point, but I'm not completely agree. Do you use release build type?

[`assert`](https://en.cppreference.com/w/cpp/error/assert) behaviour depends on `NDEBUG` definition. If we have debug build it has to call [`std:abort`](https://en.cppreference.com/w/cpp/utility/program/abort) which has `[[noreturn]]` attribute and compiler should correctly detect that this part of code is unreachable.

But in release it does nothing and this code isn't unreachable. So I think it's wrong to call `__builtin_unreachable()` here. I will return NaN here to suppress the warning.

2022-03-21 08:27 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_array_dynamic.hpp
> +        void forEachArrayEntry(const Fn& fn) {
Good point. Thanks

2022-03-21 08:28 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_array_dynamic.hpp
> +        void forEachArrayEntry(const Fn& fn) {
Good point. Thanks

2022-03-21 08:40 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/pattern_drawer.hpp
> +        template<class SomePattern>
Then a new concept that looks like this would work:
```cpp
template<typename T>
concept ArrayPattern = requires(T pattern, const std::function<void(int, Pattern&)>& fn) {
   { pattern.forEachArrayEntry(fn) } -> std::same_as<void>;
};
```

That will ensure that the template will only ever accept a type that has a `forEachArrayEntry` function with the correct parameters / return type

2022-03-21 08:41 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/pattern_drawer.hpp
> +    const u64 DISPLAY_END_DEFAULT = 50;
Actually, `static` isn't needed. `constexpr` was the important one

2022-03-21 08:45 UTC, WerWolv commented on lib/libimhex/include/hex/pattern_language/patterns/pattern_float.hpp
> +                assert(false);
I use debug builds when developing and release types for all builds made by the CI.

The problem is, `std::abort` is indeed marked as `[[noreturn]]` but `assert` cannot be because it's dependent on its parameter whether or not it's noreturn.

This is probably a bit of a bad implementation from my side and the pattern should just take an enum in the constructor instead of allowing a size to be passed in. The evaluator will only ever pass 4 or 8 to the constructor, everything else would be a bug. That's why I used `__builtin_unreachable()` elsewhere. Returning `NaN` is fine though, I'll correct this later on

2022-03-21 09:01 UTC, Diadlo commented on lib/libimhex/include/hex/pattern_language/pattern_drawer.hpp
> +        template<class SomePattern>
I haven't used concepts before. Look cool :)

2022-03-21 09:33 UTC, WerWolv approved these changes

2022-03-21 12:52 UTC, merged

2022-03-21 12:53 UTC, WerWolv commented
Thanks a lot for that immense work!