[Feature] Network proxy for hex::Net
WerWolv/ImHex pull request #562
Opened 2022-06-29 15:50 UTC by shirok1

For #557

![image](https://user-images.githubusercontent.com/12044683/176480282-bc63aff5-bff5-47a7-95cd-c57ef2ae84ed.png)

PS. I ended up just reading from setting registry `"hex.builtin.setting.proxy.url"` every time.

2022-06-29 15:55 UTC, WerWolv requested changes

2022-06-29 15:55 UTC, WerWolv commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
You're accessing things that are conceptually not known by libimhex as they are created in the built-in plugin. Even if the built-in plugin technically always is available, depending on things that get created in a plugin is really bad.

That's why I suggested adding a static member function to set this value from the built-in plugin

2022-06-29 15:57 UTC, shirok1 commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
Hmm, I think in this way, if this setting is not set, the proxy will be set to none, which is exactly what is expected to happen without built-in plugin.

2022-06-29 16:02 UTC, WerWolv commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
Of course it works fine. It just conceptually creates a dependecy of libimhex on the built-in plugin which is wrong. The built-in plugin knows of libimhex and can use it as it wishes, but libimhex knows nothing about the built-in plugin. It doesn't matter to libimhex if any plugin is being loaded or not. 

Because of this reason, libimhex should not be the one querying the information it needs from the built-in plugin but the built-in plugin should send the information to libimhex (inverting that dependency).

2022-06-29 16:04 UTC, shirok1 commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
I also referenced how you handle `"hex.builtin.setting.font.font_size"`, which is read from registry every time. (The opposite is `"hex.builtin.setting.interface.color"`, which is only read when Welcome Screen is init, but I think that is more related to UI refresh requirement)

2022-06-29 16:08 UTC, shirok1 commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
I wonder if there is a convention for initing **the** static field at startup.

2022-06-29 16:12 UTC, WerWolv commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
Yeah those two settings completely go against these principles as well and I hate it. If there was a nice way to change it, I absolutely would. 

With the Net class there is an easy way to not have a depdency like that so it's best to avoid it by adding a new function to it:

```cpp
static void setProxy(const std::string &url);
```

There's really no issue with having static functions. They are a necessity and absolutely make sense in this case as it's a global setting that should apply to every single instance of the Net class. It doesn't create or expose a global static member variable at all (which I agree with you, would be bad design) but instead creates an interface to configure how the Net class should behave in the whole program.

2022-06-29 16:26 UTC, shirok1 commented on lib/libimhex/source/helpers/net.cpp
> +        std::string proxyUrl = ContentRegistry::Settings::read("hex.builtin.setting.proxy", "hex.builtin.setting.proxy.url", "");
Oh, sorry. I didn't realize `registerSettings` is an init method, not a imgui function, until now...

2022-07-01 03:51 UTC, shirok1 commented
@WerWolv

2022-07-01 10:09 UTC, WerWolv requested changes

2022-07-01 10:09 UTC, WerWolv commented on lib/libimhex/include/hex/helpers/net.hpp
> +        static std::string m_proxyUrl;
The convention I use for these variables is prefixing them with `s_` instead of `m_` since they're static and not a member

2022-07-01 10:12 UTC, WerWolv commented on lib/libimhex/include/hex/helpers/net.hpp
> +        static std::string m_proxyUrl;
Also `Net::s_proxyUrl` instead of just `s_proxyUrl`

2022-07-01 10:13 UTC, WerWolv commented
Thanks a lot for the changes. Besides that little nitpick it looks great!

2022-07-01 11:54 UTC, shirok1 commented
Changed.

2022-07-01 12:05 UTC, WerWolv commented
Thanks a lot!

2022-07-01 12:05 UTC, merged