AUR/ArchLinux support
WerWolv/ImHex pull request #566
Opened 2022-07-02 01:20 UTC by iTrooz

This PR : 
- adds a version.txt file in the root that will be used by the entire workflow (including cmake) to define project version
- adds a ArchLinux variant (.pkg.tar.zst)
- updates the `imhex-bin` AUR package with this variant on release

As said on Discord, I would like this to be merged at the last moment, but feel free to review it in advance, as I shouldn't change many things now

2022-07-02 08:16 UTC, WerWolv requested changes

2022-07-02 08:16 UTC, WerWolv commented on version.txt
> +1.18.2
Please name this file `VERSION`

2022-07-02 08:16 UTC, WerWolv commented on dist/Arch/PKGBUILD
> +	install -DT $srcdir/usr/share/imhex/plugins/builtin.hexplug $pkgdir/usr/share/imhex/plugins/builtin.hexplug
Formatting here looks a bit wrong. Also, is it possible to use a glob here for everything in the `plugins` folder with the `.hexplug` ending? Just in case there will be more plugins in the future

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/release.yml
> +      - name: Prepare PKGBUILD
Not enough emojis!

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/build.yml
> +    name: ArchLinux Build
I'd name this something like `🐧 ArchLinux <Version>` so it fits with the rest of the names

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/build.yml
> +      - name: Update all packages and install necessary packages
`Install setup dependencies` might be better

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/build.yml
> +      - name: Package imhex-archlinux.pkg.tar.zst
`Package ArchLinux .pkg.tar.zst`

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/build.yml
> +      - name: Upload imhex-archlinux.pkg.tar.zst
`Upload ArchLinux .pkg.tar.zst`

2022-07-02 08:16 UTC, WerWolv commented on .github/workflows/build.yml
> +      - name: Update all packages and install necessary packages
Also you need more emojis here :P

2022-07-02 11:12 UTC, iTrooz commented on .github/workflows/build.yml
> +    name: ArchLinux Build
I'm not sure Arch has versions, so I'm just going to put `🐧 ArchLinux`

2022-07-02 11:21 UTC, iTrooz commented on .github/workflows/build.yml
> +      - name: Update all packages and install necessary packages
I separated them into two steps (update all packages & install setup dependencies) to make it explicit that all packages are being upgraded

2022-07-04 19:38 UTC, WerWolv approved these changes

2022-07-04 19:40 UTC, merged