fix: invariables not working, add recusive pattern scan
WerWolv/ImHex pull request #579
Opened 2022-07-11 22:07 UTC by PredatorCZ

A few things.

1. Added recursive pattern scan for mime lookup
2. In variable weren't working/crashing because of cleaning before eval, also in-vars disappeared after eval from settings.
3. Removed some dead code.

2022-07-12 10:23 UTC, WerWolv requested changes

2022-07-12 10:23 UTC, WerWolv commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> -            this->m_patternVariables.clear();
This will cause old and removed In/Out values to not be removed anymore from the list and new ones just being added on top of it.

How are In/Out values not working for you? They seem to work fine here

2022-07-12 10:24 UTC, WerWolv commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> -            this->m_patternVariables.clear();
Okay nevermind, something is broken. But this still feels like it makes it worse

2022-07-12 10:38 UTC, WerWolv commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> -            this->m_patternVariables.clear();
Okay, the issue is in fact not the clearing there, that is necessary for the above mentioned reasons, the issue is that we call `parsePatterns` with an empty string in the `clearPatterns` function which is called at the start of `evaluatePatterns`. Removing this call fixes the issue.

2022-07-12 11:29 UTC, PredatorCZ commented on plugins/builtin/source/content/views/view_pattern_editor.cpp
> -            this->m_patternVariables.clear();
I'll see what can I do about that

2022-07-14 09:36 UTC, WerWolv approved these changes

2022-07-14 09:37 UTC, merged

2022-07-14 09:37 UTC, WerWolv commented
Thank you!