Add ability to paste hex bytes with 0x
WerWolv/ImHex pull request #581
Opened 2022-07-15 10:12 UTC by Diadlo

Sometimes you may have string in the following format: `0xaa 0x1 0xbb 0x2`. It's useful to have an ability to paste them as is, without editing

2022-07-15 12:44 UTC, WerWolv requested changes
Looks like there's an issue with the submodules that got downgraded for some reason

2022-07-15 12:44 UTC, WerWolv commented on plugins/builtin/source/content/views/view_hex_editor.cpp
> +#include <sstream>
There's not really a reason to use stringstream, right?

Please avoid it if you can as it's absolutely gigantic and slows down compile times even more. As far as I can tell, you can get away by using std::string and hex::format

2022-08-20 05:19 UTC, Diadlo commented
Fixed
But to be honest, I didn't test it after that. That's because after dropping clang support it ImHex uncompilable on my Mac.

1. It doesn't check if compiler is GCC and silently stop working with clang
2. After installing and specifying GCC12 as a compiler I have a lot of issues in some macOS internals

FYI [error.log](https://github.com/WerWolv/ImHex/files/9386273/error.log)

2022-08-20 08:13 UTC, WerWolv commented
@Diadlo Thanks for the changes!

Your compile issues seem to mostly stem from objc files being compiled with gcc.
We only compile C and C++ code with gcc, everything else that's apple specific still is using clang. 

This here is the build command the CI uses which works fine there:
```
CC=$(brew --prefix gcc@12)/bin/gcc-12      \
CXX=$(brew --prefix gcc@12)/bin/g++-12  \
OBJC=$(brew --prefix llvm)/bin/clang           \
OBJCXX=$(brew --prefix llvm)/bin/clang++  \
cmake .. 
```
Basically we tell cmake to use gcc as C and C++ compiler and llvm clang as ObjC and ObjC++ compiler. It should work fine after that. If you need any more help with getting it to work, feel free to ask!

2022-08-20 08:29 UTC, Diadlo commented
@WerWolv It works. Thanks!

Now PR is tested and one issue is fixed

2022-09-01 11:50 UTC, Diadlo commented
@WerWolv Is there anything else that should be done?

2022-09-01 18:27 UTC, WerWolv requested changes

2022-09-01 18:27 UTC, WerWolv commented on plugins/builtin/source/content/views/view_hex_editor.cpp
> +#include <sstream>
Remove unused sstream and logger include

2022-09-01 18:27 UTC, WerWolv commented on plugins/builtin/source/content/views/view_hex_editor.cpp
> +        for (const char &c: input) {
What exactly does this code do? To me it looks like it's splitting the input at spaces so it could easily be replaced with the `hex::splitString` function. However, is this really a good idea? What about byte strings that look like this: `AABBCCDD`. These should be pastable as well as `AA BB CC DD` or `0xAA, 0xBB, 0xCC, 0xDD` etc. 

I think it would be better to first remove all occurrences of `0x`, `0X`, commas and whitespace characters (space, tab, newline etc) then check if there's only valid hex characters in there and at the end parse that data which should always be in the form of `AABBCCDD` then

2022-12-29 08:49 UTC, aboooody16s approved these changes

2022-12-29 14:08 UTC, closed without merging