feat: Added LEB128 in data inspector
WerWolv/ImHex pull request #615
Opened 2022-07-31 04:19 UTC by gudzpoz

This pull request adds in the ability to inspect and edit LEB128 data in the data inspector: #605

2022-07-31 13:33 UTC, WerWolv requested changes

2022-07-31 13:33 UTC, WerWolv commented on lib/libimhex/source/helpers/utils.cpp
> +    template<typename T>
I put these kind of things into crypto.cpp/crypto.hpp usually

2022-07-31 13:33 UTC, WerWolv commented on plugins/builtin/source/lang/en_US.cpp
> +                { "hex.builtin.inspector.sleb128", "Signed LEB128" },
Please add commented out placeholders for these two translations to all the other language files as well so it won't be forgotted when translations get updated

2022-07-31 13:33 UTC, WerWolv commented on lib/libimhex/include/hex/api/content_registry.hpp
> +                    size_t maxSize = 0;
This should probably be set explicitly to 0 in the `add` function instead of being done in here

2022-07-31 13:33 UTC, WerWolv commented
Thanks a lot for the PR!

2022-08-01 03:19 UTC, gudzpoz commented on plugins/builtin/source/lang/en_US.cpp
> +                { "hex.builtin.inspector.sleb128", "Signed LEB128" },
Added. Thanks!

2022-08-01 03:29 UTC, gudzpoz commented
Thanks for the review! I have made modifications accordingly. Would you please review it again?

2022-08-01 08:37 UTC, WerWolv approved these changes

2022-08-01 11:20 UTC, merged

2022-08-01 11:20 UTC, WerWolv commented
Thanks a lot!