Fedora build fix
WerWolv/ImHex pull request #642
Opened 2022-08-03 08:42 UTC by iTrooz

This pull requests :
- detect the folders to install to with GNUInstallDirs (for example lib64 on Fedora)
- Moves the builtin plugin to /usr/lib/imhex/builtin.hexplug, and and search that folder in fs.cpp (As Fedora do not want plugins in /usr/share/imhex/plugins)

(Further discussed on Discord)

This should be enough to allow official Fedora packaging

NOTE : This is not to be merged now, I didn't test my changes anywhere
I would appreciate people testing this on various systems (mostly Linux distributions as I don't think I've touched Windows/MacOS builds) and reporting here

2022-08-03 08:45 UTC, iTrooz commented
Oh wait, fs.cpp was refactored

2022-08-03 08:56 UTC, iTrooz commented
Okay this should be good now !

2022-08-03 08:56 UTC, iTrooz commented
Tested on ArchLinux (KDE)

2022-08-03 09:00 UTC, WerWolv requested changes

2022-08-03 09:00 UTC, WerWolv commented on cmake/build_helpers.cmake
> +        add_compile_definitions(SYSTEM_PLUGINS_LOCATION="${CMAKE_INSTALL_FULL_LIBDIR}/imhex")
Won't this cause issues with e.g the AppImage or the flatpak? Since those can be used on multiple distros

2022-08-03 09:03 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
Do you prefer `result = appendPath(getPluginPaths(), "constants");` or `result = getPluginPaths());` ?

2022-08-03 09:06 UTC, WerWolv commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
`result = appendPath(getPluginPaths(), "plugins");` is probably better

2022-08-03 09:07 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
Hummm forget about it, I was dumb sorry lol

2022-08-03 09:21 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
I did what I could with [893f8a9](https://github.com/WerWolv/ImHex/pull/642/commits/893f8a966f0dcd89c1dd6374bbe17fd52b765b2d), but I'm not sure it's better

2022-08-03 09:22 UTC, iTrooz commented on cmake/build_helpers.cmake
> +        add_compile_definitions(SYSTEM_PLUGINS_LOCATION="${CMAKE_INSTALL_FULL_LIBDIR}/imhex")
I don't think so because it shouldn't try to load a library outside its image, it would be nice to have someone on Fedora test it tho

2022-08-03 09:25 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
(I couldn't do `result = appendPath(getPluginPaths(), "plugins");` afterall because /usr/lib/imhex do not need the "plugins" suffix)

2022-08-03 09:39 UTC, WerWolv commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
I'd still like to have the plugins folder inside of the imhex folder. Just in case we'll be putting more stuff there (for any kind of reason)

2022-08-03 09:42 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
In this case (making a directory structure for libraries) should we move libimhex.so to /usr/lib/imhex ?

2022-08-03 09:43 UTC, WerWolv commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
I don't think so because only /usr/lib will be in the library search path, /usr/lib/imhex will not be

2022-08-03 10:45 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
Should be good now !

2022-08-03 10:48 UTC, iTrooz commented
Ooops sorry, I just discovered the button to request a review

2022-08-03 10:56 UTC, iTrooz commented on lib/libimhex/source/helpers/fs.cpp
> +                result.push_back(SYSTEM_PLUGINS_LOCATION);
> I don't think so because only /usr/lib will be in the library search path, /usr/lib/imhex will not be

(I tested this and yeah you're right)

2022-08-03 11:26 UTC, WerWolv approved these changes

2022-08-03 20:19 UTC, iTrooz commented
I know I forgot something, but I don't know what, so here is my PR !
Here is an updated recap of what it does :
- Switch to GNUInstallDirs to set the lib/bin/whatever folders to install to
- Store plugins in `lib/imhex/plugins/*.hexplug` instead of `share/imhex/*.hexplug` in every package **except the AppImage package** because it can't detect the `lib/imhex/plugins/*.hexplug` folder

2022-08-03 20:22 UTC, iTrooz commented
I think this should be tested thoroughly
I currently tested the ArchLinux pkg and the AppImage on ArchLinux KDE (and I didn't test them thoroughly because I don't use ImHex a lot outside of packaging it). The other packages (.deb and .rpm) are not tested at all

2022-08-04 14:14 UTC, iTrooz commented
I check the AppImage and the deb on on Ubuntu 22.04
Fun fact : since they don't share the same paths for plugins they can coexist, thus closing #544 per this PR

2022-08-04 14:17 UTC, iTrooz commented
Tested the AppImage on Fedora 35, and it works
Couldn't test the RPM because Fedora 36/37 is needed, someone should do this

2022-08-04 16:09 UTC, iTrooz commented
A friend tested the rpm on Fedora 36 KDE - Everything is working !

2022-08-04 17:45 UTC, iTrooz commented
This fixes #262

2022-08-04 18:37 UTC, merged