add NoGPU (Software Rendering) version for Windows
WerWolv/ImHex pull request #716
Opened 2022-08-31 16:30 UTC by iTrooz

2022-08-31 16:30 UTC, iTrooz commented
Should be ready to be merged (tested on a Win11 VM)

2022-09-01 18:31 UTC, WerWolv requested changes

2022-09-01 18:31 UTC, WerWolv commented on .github/workflows/build.yml
> +    - name: Download Mesa3D for NoGPU version
Missing emoji.
Maybe something like `⬇️ Download NoGPU dependencies` so we can call it the same on all OSes

2022-09-01 18:31 UTC, WerWolv commented on .github/workflows/release.yml
> +          mv "Windows Portable NoGPU.zip" imhex-${{env.IMHEX_VERSION}}-Windows-Portable.zip
NoGPU is missing in the output name here

2022-09-01 23:18 UTC, iTrooz commented on .github/workflows/release.yml
> +          mv "Windows Portable NoGPU.zip" imhex-${{env.IMHEX_VERSION}}-Windows-Portable.zip
Oops my mistake

2022-09-01 23:25 UTC, iTrooz commented on .github/workflows/build.yml
> +    - name: Download Mesa3D for NoGPU version
If you don't mind, I'd like to keep it like that, so we can know explicitly what this step does just by glancing
+ it would be difficult to use that step name for MacOS since there are two steps ("Checkout glfw" and "Patch and install custom glfw")
(And Linux doesn't need such a step because the normal version can already run in software rendering, at least I was able to run it on VMs)

It's your call tho

2022-09-02 14:11 UTC, WerWolv approved these changes

2022-09-02 14:12 UTC, merged