Clean PKGBUILD
WerWolv/ImHex pull request #732
Opened 2022-09-07 18:54 UTC by iTrooz

As discussed on Discord : https://discord.com/channels/789833418631675954/789833418631675957/1016713453030887524

@Foxboron if you want to take a look ^^

2022-09-07 19:16 UTC, WerWolv requested changes

2022-09-07 19:16 UTC, WerWolv commented on dist/Arch/PKGBUILD
> +pkgver=1.22.0
I'd really like to avoid having to update the version in here every time

2022-09-07 20:15 UTC, iTrooz commented on dist/Arch/PKGBUILD
> +pkgver=1.22.0
OOPS, really sorry, I forgot about it, I did it to test the PKGBUILD

2022-09-07 20:22 UTC, WerWolv approved these changes

2022-09-07 20:23 UTC, merged

2022-09-07 20:24 UTC, WerWolv commented
Thank you!

2022-09-08 10:50 UTC, Foxboron commented
Looks fine, thanks @iTrooz :)