Minor additions
WerWolv/ImHex pull request #789
Opened 2022-10-19 12:26 UTC by iTrooz

The commit names are self-explanatory

I really would like a code review ^^

2022-10-19 12:33 UTC, WerWolv requested changes

2022-10-19 12:33 UTC, WerWolv commented on lib/libimhex/source/helpers/net.cpp
> +            char *url = NULL;
C++ has a nice keyword called `nullptr` that should be used instead of `NULL`

2022-10-19 12:33 UTC, WerWolv commented on main/source/init/splash_window.cpp
> +                    using namespace std::chrono;
Using namespace is very frouned upon since it dumps the entire content of the namespace into your current namespace. I don't think it's needed here really.

I use it above for chrono_literals because you can't use user defined literals (Such as writing `100ms` to refer to `std::chrono::milliseconds(100)`) without a using namespace. But that only dumps like 5 functions into your namespace instead of the entirety of the chrono library

2022-10-19 12:35 UTC, WerWolv requested changes

2022-10-19 12:35 UTC, WerWolv commented on main/source/init/splash_window.cpp
> +                    log::info("Task {} done in {}ms", name, duration_cast<milliseconds>(endTime-startTime).count());
`"Task {} finished in {} ms"` sounds better in my opinion

2022-10-19 12:35 UTC, WerWolv commented
Thank you!

2022-10-19 12:37 UTC, iTrooz commented on main/source/init/splash_window.cpp
> +                    using namespace std::chrono;
> I use it above for chrono_literals

Oops, how did I not see that

In this case, should I use `std::chrono::` everywhere ?

2022-10-19 12:39 UTC, WerWolv commented on main/source/init/splash_window.cpp
> +                    using namespace std::chrono;
Yeah that's usually better. There's really only very very few good usecases where `using namespace` makes your code better. For `std` types, you should generally avoid it.

2022-10-20 06:27 UTC, WerWolv approved these changes

2022-10-20 06:27 UTC, WerWolv commented
Thank you!

2022-10-20 06:28 UTC, merged