Modifications to Content store
WerWolv/ImHex pull request #795
Opened 2022-10-23 10:44 UTC by iTrooz

I think the commit names already explain the changelog

2022-10-23 10:44 UTC, iTrooz commented
https://github.com/WerWolv/ImHex/issues/794

2022-10-26 07:11 UTC, WerWolv requested changes

2022-10-26 07:11 UTC, WerWolv commented on plugins/builtin/include/content/views/view_store.hpp
> +        Inprogress,
`InProgress`

2022-10-26 07:11 UTC, WerWolv commented on plugins/builtin/source/content/views/view_store.cpp
> +                if(this->m_requestStatus==RequestStatus::NotAttempted)
Missing spaces before and after `==`

2022-10-26 07:11 UTC, WerWolv commented on plugins/builtin/source/content/views/view_store.cpp
> +        if(this->m_requestStatus == RequestStatus::Inprogress)return;
Missing space between `if` and `(`. `return` can go on a new line

2022-10-26 07:11 UTC, WerWolv commented on plugins/builtin/source/content/views/view_store.cpp
> +                ImGui::TextFormattedColored(ImGui::GetCustomColorVec4(ImGuiCustomCol_ToolbarRed), "Request failed !");
Remove the space before the `!`. This should probably also go into the localization files

2022-10-26 07:39 UTC, iTrooz commented
Done !

2022-10-27 11:12 UTC, merged