Add a setting to disable loading of unicode characters
WerWolv/ImHex pull request #798
Opened 2022-10-24 14:48 UTC by iTrooz

Helps #796

2022-10-26 07:09 UTC, WerWolv requested changes

2022-10-26 07:09 UTC, WerWolv commented on plugins/builtin/source/lang/en_US.cpp
> +                    { "hex.builtin.setting.general.enable_unicode", "Load unicode characters (will speed up startup but some characters may not appear)" },
This text is a bit misleading I think. What it says to me is, If I turn this setting on and have it load unicode characters, it will speed up the loading process.

I'd just call it `Load unicode characters`. There isn't much space for a comment like this anyways.

Also please add the same string to all the other language files but comment it out there.

2022-10-26 07:22 UTC, iTrooz commented on plugins/builtin/source/lang/en_US.cpp
> +                    { "hex.builtin.setting.general.enable_unicode", "Load unicode characters (will speed up startup but some characters may not appear)" },
Oops yeah, I didn't think it through

2022-10-26 07:25 UTC, iTrooz commented on plugins/builtin/source/lang/en_US.cpp
> +                    { "hex.builtin.setting.general.enable_unicode", "Load unicode characters (will speed up startup but some characters may not appear)" },
Done !

2022-10-27 11:10 UTC, WerWolv approved these changes

2022-10-27 11:11 UTC, merged