Ask the users for updates
WerWolv/ImHex pull request #803
Opened 2022-10-27 21:46 UTC by iTrooz

2022-10-28 11:00 UTC, iTrooz commented
https://github.com/WerWolv/ImHex/issues/794

2022-10-28 13:03 UTC, WerWolv requested changes

2022-10-28 13:03 UTC, WerWolv commented on main/source/init/tasks.cpp
> +        int showCheckForUpdates = ContentRegistry::Settings::read("hex.builtin.setting.general", "hex.builtin.setting.general.check_for_updates", 2);
Could you document in a comment what the different values for this setting mean? 0, 1 and 2 alone aren't really self explanatory

2022-10-28 13:03 UTC, WerWolv commented on main/source/init/tasks.cpp
> +        if(showCheckForUpdates==1){
Spaces before and after operator are missing

2022-10-28 13:03 UTC, WerWolv commented on plugins/builtin/source/content/settings_entries.cpp
> +        ContentRegistry::Settings::add("hex.builtin.setting.general", "hex.builtin.setting.general.check_for_updates", 2, [](auto name, nlohmann::json &setting) {
1 and 2 will both be treated here as "Enabled". Is that the desired effect?

2022-10-28 13:03 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +            if(showCheckForUpdates==2){
Spaces before and after operator are missing

2022-10-28 13:03 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Formatting of the lambdas here is kinda weird. I'd put the head of the lambda and its content on two different lines and also move the head of the first lambda on a new line

2022-10-28 13:03 UTC, WerWolv commented on plugins/builtin/source/lang/en_US.cpp
> +                { "hex.builtin.welcome.check_for_updates", "Check for updates" },
These should also be added to the other language files

2022-10-28 13:03 UTC, WerWolv commented
Thank you!

2022-10-28 19:29 UTC, iTrooz commented on main/source/init/tasks.cpp
> +        int showCheckForUpdates = ContentRegistry::Settings::read("hex.builtin.setting.general", "hex.builtin.setting.general.check_for_updates", 2);
Sure ! Actually, aren't enums just named integers in C++ ? In this case, may I create an enum somewhere ? (I'm not sure where that would fit)

2022-10-28 19:30 UTC, iTrooz commented on main/source/init/tasks.cpp
> +        if(showCheckForUpdates==1){
Oops, sorry for making you repeat yourself in this PR, I should have checked

2022-10-28 19:35 UTC, iTrooz commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Like that ? (see my last commit)

2022-10-29 18:36 UTC, WerWolv approved these changes

2022-10-29 18:36 UTC, WerWolv commented on main/source/init/tasks.cpp
> +        int showCheckForUpdates = ContentRegistry::Settings::read("hex.builtin.setting.general", "hex.builtin.setting.general.check_for_updates", 2);
Yeah an enum would be great for this too. Just requires some casting when writing it to the json object probably

2022-10-29 18:37 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Yeah an enum would be great for this too. Just requires some casting when writing it to the json object probably

2022-10-29 18:41 UTC, iTrooz commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Where should I create the enum ? We would need it in `main` and `builtin`, so how about in `tasks.hpp` ?

2022-10-29 19:22 UTC, WerWolv commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Right it's split up between multiple files...
Yeah I honestly also don't know where to put it best.
For now I'd probably just put a comment above the definition of the setting.

2022-10-29 21:41 UTC, iTrooz commented on plugins/builtin/source/content/welcome_screen.cpp
> +                View::showYesNoQuestionPopup("hex.builtin.welcome.check_for_updates_text"_lang, [] {
Done !

2022-10-29 21:43 UTC, WerWolv approved these changes

2022-10-29 21:43 UTC, merged

2022-10-29 21:43 UTC, WerWolv commented
Thank you!